### see all or specific donation
http://localhost:80/api/donations

### see all or specific donation message
http://localhost:80/api/donation/messages

### create a donation
POST http://localhost:80/api/donations HTTP/1.1
Content-Type: application/json

{
  "comment": "he",
  "amount": "23"
}

### pay for specific donation
POST http://localhost:80/api/payment/secret
Content-Type: application/json

{
  "id": 6
}

