version: '3'
services:
  client:
    build: 
      context: ../client
      dockerfile: Dockerfile.dev
    volumes: 
      - ../client:/app
    networks: 
      - nginx_network

  nginx:
    image: nginx:1.19-alpine
    ports:
      - 80:80
    volumes: 
      - ./nginx/templates:/etc/nginx/templates
    restart: always
    environment:
      NGINX_HOST: _
    restart: always
    networks:
      - nginx_network

  worker:
    build:
      context: ../worker
      dockerfile: Dockerfile.dev
    networks:
      - queue_network
    environment: 
      - NODE_ENV=production
      - NATS_URI=http://broker:4222
      - NATS_CLUSTER_ID=queue
      - NATS_CLIENT_ID=work #{{.Task.Name}}
    depends_on: 
      - broker
    volumes: 
      - ../worker:/app
    #restart: always

  api:
    build:
      context: ../api
      dockerfile: Dockerfile.dev
    ports:
      - 3000:3000
    networks:
      - queue_network
    environment: 
      - NODE_ENV=production
      - NATS_URI=http://broker:4222
      - NATS_CLUSTER_ID=queue
      - NATS_CLIENT_ID=api
    volumes: 
      - ../api:/app
    depends_on: 
      - broker

  broker:
    image: nats-streaming:0.17.0
    ports:
      - 4222:4222
      - 8222:8222
    command: [
      '-p',
      '4222',
      '-m', 
      '8222',
      '-hbi',
      '5s',
      '-hbt',
      '5s',
      '-hbf',
      '2',
      '-SD',
      '-cid',
      'queue'
    ]
    networks:
      - queue_network
  
networks:
  queue_network:
  nginx_network: