version: '3'
services:
  client:
    build: 
      context: ../client
      dockerfile: Dockerfile
    ports: 
      - 8080:3000
    volumes: 
      - ../client:/app

  worker:
    build:
      context: ../worker
      dockerfile: Dockerfile
    networks:
      - queue_network
    environment: 
      - NODE_ENV=production
      - NATS_URI=http://broker:4222
      - NATS_CLUSTER_ID=queue
      - NATS_CLIENT_ID=worker
    depends_on: 
      - broker
    volumes: 
      - ../worker:/app
    #restart: always

  api:
    build:
      context: ../api
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    networks:
      - queue_network
    environment: 
      - NODE_ENV=production
      - NATS_URI=http://broker:4222
      - NATS_CLUSTER_ID=queue
      - NATS_CLIENT_ID=api
    volumes: 
      - ../api:/app
    depends_on: 
      - broker

  broker:
    image: nats-streaming:0.17.0
    ports:
      - 4222:4222
      - 8222:8222
    command: [
      '-p',
      '4222',
      '-m', 
      '8222',
      '-hbi',
      '5s',
      '-hbt',
      '5s',
      '-hbf',
      '2',
      '-SD',
      '-cid',
      'queue'
    ]
    networks:
      - queue_network
  
networks:
  queue_network: