version: '3'
services:
  postgres:
    image: postgres:13-alpine
    ports:
      - 5432:5432
    networks: 
      - queue_network
    environment: 
      - POSTGRES_PASSWORD=pass
      - POSTGRES_USER=user
      - POSTGRES_DB=db_1
    volumes:
      - ./postgres/init.dev.sql:/docker-entrypoint-initdb.d/init.sql

  worker:
    build:
      context: ../worker
      dockerfile: Dockerfile.dev
    networks:
      - queue_network
    environment: 
      - NODE_ENV=production
      - NATS_URI=http://broker:4222
      - NATS_CLUSTER_ID=queue
      - NATS_CLIENT_ID=worker
    depends_on: 
      - broker
    volumes: 
      - ../worker:/app
    #restart: always

  api:
    build:
      context: ../api
      dockerfile: Dockerfile.dev
    networks:
      - queue_network
      - nginx_network
    ports: 
      - 3000:3000
    environment: 
      - NODE_ENV=production
      - NATS_URI=http://broker:4222
      - NATS_CLUSTER_ID=queue
      - NATS_CLIENT_ID=api
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=user
      - DB_PASSWORD=pass
      - DB_NAME=db_1
    volumes: 
      - ../api:/app
    depends_on: 
      - broker

  broker:
    image: nats-streaming:0.17.0
    ports:
      - 4222:4222
      - 8222:8222
    command: [
      '-p',
      '4222',
      '-m', 
      '8222',
      '-hbi',
      '5s',
      '-hbt',
      '5s',
      '-hbf',
      '2',
      '-SD',
      '-cid',
      'queue'
    ]
    networks:
      - queue_network
  
networks:
  queue_network:
  nginx_network: